apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pjky63ssb-nodejs
  janus-idp.io/tekton: pjky63ssb-nodejs
  backstage.io/kubernetes-id: pjky63ssb-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pjky63ssb-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
