apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pjky63ssb-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pjky63ssb-nodejs 
  name: pjky63ssb-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pjky63ssb-nodejs 
